// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpdUJ3uzV45Ds2oL5YW3mfKRnSvbXjCmM',
    appId: '1:251183071772:web:e26db57b6947ec456055d9',
    messagingSenderId: '251183071772',
    projectId: 'my-first-project-ef06c',
    authDomain: 'my-first-project-ef06c.firebaseapp.com',
    storageBucket: 'my-first-project-ef06c.appspot.com',
    measurementId: 'G-FW87VDY76J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCON7GqCk402uK_s0S9iZ6ykxmaBBQLnVw',
    appId: '1:251183071772:android:7d11a10ff650aa3f6055d9',
    messagingSenderId: '251183071772',
    projectId: 'my-first-project-ef06c',
    storageBucket: 'my-first-project-ef06c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzJMwCQcEOBM8XtizGMfQyklthlX4PWpk',
    appId: '1:251183071772:ios:3178399a9b1a191c6055d9',
    messagingSenderId: '251183071772',
    projectId: 'my-first-project-ef06c',
    storageBucket: 'my-first-project-ef06c.appspot.com',
    iosClientId: '251183071772-ivgaaaoapitqbu7q467q5nfcnkpa937u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzJMwCQcEOBM8XtizGMfQyklthlX4PWpk',
    appId: '1:251183071772:ios:3178399a9b1a191c6055d9',
    messagingSenderId: '251183071772',
    projectId: 'my-first-project-ef06c',
    storageBucket: 'my-first-project-ef06c.appspot.com',
    iosClientId: '251183071772-ivgaaaoapitqbu7q467q5nfcnkpa937u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
